// This is UserDataActionType.js

export const GETUSERID = "GETUSERID";

export const GETUSEREMAIL = "GETUSEREMAIL";

export const GETUSERNAME = "GETUSERNAME";

export const GETUSERIMAGE = "GETUSERIMAGE";

export const LOGOUTUSER = "LOGOUTUSER";

export const GETADMINEMAIL = "GETADMINEMAIL";

export const GETADMINNAME = "GETADMINNAME";

export const GET_ALL_USER_DATA_REQUEST = "GET_ALL_USER_DATA_REQUEST";
export const GET_ALL_USER_DATA_SUCCESS = "GET_ALL_USER_DATA_SUCCESS";
export const GET_ALL_USER_DATA_FAILURE = "GET_ALL_USER_DATA_FAILURE";
